In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
x.shape

(40,)

In [7]:
x.dtype

dtype('int32')

In [2]:
import numpy as np

In [3]:
np.version.version
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [6]:
x.ndim

1

In [7]:
y=np.array([1,1,1,1,1,1,1,1])
y == 1

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [19]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
a=np.ones((4,4,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
c=np.arange(1,10)
c

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [31]:
c=c[::-1]
c

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [33]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr= np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [21]:
arr=arr.astype('float32')
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [1]:
import numpy as np

In [8]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [13]:
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [14]:
np.minimum(arr1,arr2)

array([[0., 2., 1.],
       [4., 2., 6.]])

In [15]:
np.maximum(arr1,arr2)

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

In [18]:
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

In [20]:
arr1<arr2

array([[False,  True, False],
       [ True, False,  True]])

In [29]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [33]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [45]:
arr3=np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr3[5:9]=12
arr3

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [48]:
x=np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [62]:
arr3d = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
arr3d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [64]:
arr3d[0]=64
arr3d

array([[64, 64, 64, 64, 64, 64],
       [ 7,  8,  9, 10, 11, 12]])

In [65]:
arr1d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr1d[0]

array([1, 2, 3])

In [23]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr2d[1:-1,1:-1]

array([[5]])

In [26]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d[0:2,2: ]

array([[3],
       [6]])

In [29]:
d=np.random.randn(10,10)
d

array([[-0.48355944, -0.34863421, -0.59352607, -0.35547864, -1.09971868,
         0.09391404,  0.21169912, -0.01119965, -0.63719574, -1.59231101],
       [-0.93474938, -0.11394483, -0.28627881, -0.28430764, -0.67346977,
        -0.8734241 , -1.64946818, -2.0191061 ,  1.09110983,  0.50032996],
       [ 0.71091638, -0.71321434, -0.20716698,  1.44228237, -0.95007327,
         0.29555629, -0.3296052 ,  0.36387406,  1.76927039,  0.73582598],
       [ 0.06385855, -0.68676783,  0.03560278, -0.20026433,  1.0401994 ,
         0.97985067,  1.4861974 ,  0.16517827,  1.16333843, -1.82821726],
       [-1.95302041, -1.7671145 , -0.30627546, -0.35117857,  0.83247297,
        -1.74781632, -1.4981972 ,  1.06381279,  0.74137885,  0.77039993],
       [-1.73269003,  1.74796193, -1.27788315, -0.65750828,  0.45145515,
        -1.10948394,  0.06771227,  0.979493  ,  1.08191732,  0.73720027],
       [ 1.82444221,  0.61968884, -0.86138485, -0.21423697,  0.16552066,
        -1.03378653, -0.47969876,  0.77937434

In [37]:
dmax, dmin= d.max(), d.min()
dmax, dmin

(1.824442209484642, -2.139123245017851)

In [45]:
a1=np.array((1,2,3,2,3,4,3,4,5,6))
a1

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [46]:
b1=np.array((7,2,10,2,7,4,9,4,9,8))
b1

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [47]:
np.intersect1d(a1, b1)

array([2, 4])

In [49]:
a2 = np.array((1,2,3,2,3,4,3,4,5,6))
a2

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [50]:
b2 = np.array((7,2,10,2,7,4,9,4,9,8))
b2

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [53]:
a2 = np.array((1,2,3,2,3,4,3,4,5,6))
b2 = np.array((7,2,10,2,7,4,9,4,9,8))
a2, b2

(array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]),
 array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8]))

In [54]:
np.where(a2 == b2)

(array([1, 3, 5, 7], dtype=int64),)

In [56]:
names = np.array(('Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'))
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [57]:
data = np.random.randn(7, 4)
data

array([[-0.42868276, -0.41772387,  2.84930436,  0.20741162],
       [ 0.00431238, -0.5079136 ,  0.22497004,  1.85950377],
       [ 0.69238762,  0.77153906, -1.55123421,  1.02998491],
       [-0.31255006, -0.85694094, -1.15320538,  1.12234487],
       [-0.79161733, -1.24481972,  0.77094026, -0.63785639],
       [-0.72785233, -0.58340802,  0.12098683,  0.71521511],
       [ 0.00557641, -2.32396913,  3.19761686,  0.73558899]])

In [58]:
data[names != "Will"]

array([[-0.42868276, -0.41772387,  2.84930436,  0.20741162],
       [ 0.00431238, -0.5079136 ,  0.22497004,  1.85950377],
       [-0.31255006, -0.85694094, -1.15320538,  1.12234487],
       [-0.72785233, -0.58340802,  0.12098683,  0.71521511],
       [ 0.00557641, -2.32396913,  3.19761686,  0.73558899]])

In [59]:
data[names == "Bob"]

array([[-0.42868276, -0.41772387,  2.84930436,  0.20741162],
       [-0.31255006, -0.85694094, -1.15320538,  1.12234487]])

In [70]:
two_d = np.arange(1,16).reshape(5,3)
two_d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [78]:
three_d = np.arange(1,17).reshape(2,2,4)
three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [79]:
np.transpose(three_d)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

In [83]:
s = np.random.randint(10)
s

3

In [84]:
np.sqrt(s)

1.7320508075688772

In [85]:
np.where(s<0.5,0,1)

array(1)

In [1]:
import numpy as np

In [3]:
ar1=np.random.randn((12))
ar1

array([ 0.6211263 , -0.17329013,  0.06192041,  0.08930034, -0.58877212,
       -0.33933445,  1.87090523, -0.09989686, -0.2942709 ,  2.20482162,
        1.27107068, -1.66373835])

In [4]:
ar2=np.random.randn((12))
ar2

array([ 0.90841739,  2.63691378,  0.98982565, -0.32576912, -1.16879776,
        1.65584296,  0.16205362, -0.46170172, -1.02923852, -1.3990921 ,
       -0.06941748, -2.32478215])

In [5]:
np.maximum(ar1,ar2)

array([ 0.90841739,  2.63691378,  0.98982565,  0.08930034, -0.58877212,
        1.65584296,  1.87090523, -0.09989686, -0.2942709 ,  2.20482162,
        1.27107068, -1.66373835])

In [7]:
names = np.array(('Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'))
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [10]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [11]:
a = np.array((1,2,3,4,5))
b = np.array((5,6,7,8,9))
a, b

(array([1, 2, 3, 4, 5]), array([5, 6, 7, 8, 9]))

In [12]:
a != b

array([ True,  True,  True,  True,  True])

In [13]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [16]:
sampleArray = np.array([[34,43,73], [82,22,12], [53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [17]:
newColumn = np.array([[10,10,10]])
newColumn

array([[10, 10, 10]])

In [27]:
np.insert(sampleArray, 2, [10,10,10], axis=1)

array([[34, 43, 10, 73],
       [82, 22, 10, 12],
       [53, 94, 10, 66]])

In [33]:
x = np.array([1., 2., 3., 4., 5., 6.]) 
y = np.array([6., 23., -1, 7, 8, 9])
x, y

(array([1., 2., 3., 4., 5., 6.]), array([ 6., 23., -1.,  7.,  8.,  9.]))

In [34]:
x.dot(y)

171.0

In [35]:
m=np.random.randn(20)
m

array([-0.23996384,  0.35579052,  0.42244724,  0.85991968,  0.50411231,
       -1.49416174, -0.45568032, -1.11547612,  0.98605743, -0.54617511,
        0.94059377,  0.5115477 , -0.6627393 ,  0.75986672, -0.10666378,
       -0.18814117, -0.59421642,  0.01957868,  1.28526887, -0.43917175])

In [36]:
np.cumsum(m)

array([-0.23996384,  0.11582668,  0.53827392,  1.39819361,  1.90230591,
        0.40814417, -0.04753615, -1.16301227, -0.17695484, -0.72312994,
        0.21746383,  0.72901153,  0.06627223,  0.82613895,  0.71947518,
        0.531334  , -0.06288241, -0.04330373,  1.24196514,  0.80279339])